type = struct PET_ESSENCE {
    unsigned int id;
    unsigned int id_type;
    namechar name[32];
    char file_model[128];
    char file_icon[128];
    unsigned int character_combo_id;
    int level_max;
    int level_require;
    float hp_a;
    float hp_b;
    float hp_c;
    float hp_gen_a;
    float hp_gen_b;
    float hp_gen_c;
    float damage_a;
    float damage_b;
    float damage_c;
    float damage_d;
    float speed_a;
    float speed_b;
    float attack_a;
    float attack_b;
    float attack_c;
    float armor_a;
    float armor_b;
    float armor_c;
    float physic_defence_a;
    float physic_defence_b;
    float physic_defence_c;
    float physic_defence_d;
    float magic_defence_a;
    float magic_defence_b;
    float magic_defence_c;
    float magic_defence_d;
    float size;
    float damage_delay;
    float attack_range;
    float attack_speed;
    int sight_range;
    unsigned int food_mask;
    unsigned int inhabit_type;
    unsigned int stand_mode;
}
